name: ml_tooling
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=0.24.2
  - numpy=1.16.3
  - scikit-learn=0.20.3
  - matplotlib=3.0.3
  - gitpython=2.1.11
  - pyyaml=5.1
  - pytest=4.4.1
  - pytest-cov=2.7.1
  - flake8=3.7.7
